apiVersion: v1
appVersion: [[ .Version ]]
description: A Helm chart used to test DNS status
engine: gotpl
home: https://github.com/giantswarm/dns-tester
name: dns-tester
sources:
  - https://github.com/giantswarm/dns-tester
version: [[ .Version ]]
annotations:
  application.giantswarm.io/team: phoenix

